version: "3.3"

services:
  smooth-bot:
    container_name: smooth-bot
    image: ghcr.io/dappnode/smooth-bot:latest
    environment:
      CONSUMER_KEY: ""
      CONSUMER_SECRET: ""
      ACCESS_TOKEN: ""
      ACCESS_TOKEN_SECRET: ""
      BEARER_TOKEN: ""
    restart: always
    volumes:
      - ./data:/app/data
