version: "3.3"

services:
  smooth-bot:
    container_name: smooth-bot
    image: ghcr.io/dappnode/smooth-bot:latest
    env_file:
      - .env
    restart: always
    volumes:
      - ./data:/app/data
